version: '2'
services:
  images-service:
    build: .
    image: leealbert95/images-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=192.168.99.100 
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - redis
    networks:
      - redis-net
  redis: 
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
networks:
  redis-net:
     driver: bridge
volumes:
  redis-data: